name: Cypress CI/CD Workflow

on: 
  push:

jobs:
  login-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Depencencies
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
      - run: npm ci
      - name: Run Login Test
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev
          wait: http://localhost:8008
          spec: cypress/login-check/login.cy.js
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: videos
          path: cypress/videos
  payments:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Depencencies
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
      - run: npm ci
      - name: Run Payments Test
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev
          wait: http://localhost:8008
          spec: cypress/payments/payments.cy.js
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: videos
          path: cypress/videos